export const FORMULARIO_APLICACION = 'FORMULARIO_APLICACION';
export const OBTENER_APLICACIONES = 'OBTENER_APLICACIONES';
export const USUARIO_APLICACIONES = 'USUARIO_APLICACIONES';
export const AGREGAR_APLICACION = 'AGREGAR_APLICACION';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const APLICACION_ACTUAL = 'APLICACION_ACTUAL';
export const ELIMINAR_APLICACION = 'ELIMINAR_APLICACION';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
